networks:
  art-museum-dev:
    driver: bridge

volumes:
  kafka_data:
    name: kafka_data_volume
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - art-museum-dev

  kafka:
    image: 'bitnami/kafka:latest'
    user: root
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - art-museum-dev
    depends_on:
      - zookeeper

  mail-dev:
    container_name: mail-dev-sec
    image: maildev/maildev
    ports:
      - ${GET_MAILS_HOST_PORT}:1080
      - ${SEND_MAILS_HOST_PORT}:1025
    networks:
      - art-museum-dev

